Improved testsuite by allowing explicit sets of back-ends.

diff --git a/testsuite/Makefile.am b/testsuite/Makefile.am
--- a/testsuite/Makefile.am
+++ b/testsuite/Makefile.am
@@ -4,17 +4,24 @@ CLEANFILES = $(wildcard failures-*.log)
 check: check-indep check-coq check-holl
 
 check-backend:
-	logfile="failures-$(BACKEND)-$$(date -Idate).log"; \
+	@logfile="failures-$(BACKEND)-$$(date -Idate).log"; \
 	cat /dev/null > log.tmp; \
 	cat /dev/null > "$$logfile"; \
 	for f in $(EXTRA_DIST); do \
-	  ../src/gappa -B$(BACKEND) < "$$f" > /dev/null 2> output.tmp; \
-	  return_code=$$?; \
-	  if [ $${return_code} -ne 0 ]; then \
-	    (echo "*** $$f exited with error code $${return_code}"; cat output.tmp; echo) >> "$$logfile"; \
-	    echo "$$f exited with error code $${return_code}" >> log.tmp; \
+	  execute=0; \
+	  if grep -e '^# back-end:' "$$f" > /dev/null; then \
+	    grep -e '^# back-end:.*'$(BACKEND) "$$f" > /dev/null; \
+	    execute=$$?; \
 	  fi; \
-	  rm output.tmp; \
+	  if [ $$execute -eq 0 ]; then \
+	    ../src/gappa -B$(BACKEND) < "$$f" > /dev/null 2> output.tmp; \
+	    return_code=$$?; \
+	    if [ $${return_code} -ne 0 ]; then \
+	      (echo "*** $$f exited with error code $${return_code}"; cat output.tmp; echo) >> "$$logfile"; \
+	      echo "$$f exited with error code $${return_code}" >> log.tmp; \
+	    fi; \
+	    rm output.tmp; \
+	  fi; \
 	done; \
 	nb=$$(cat log.tmp | wc -l); \
 	if [ $$nb -gt 0 ]; then \
